[base]
package = ocean
env_name = quad_meshing

[vec]
total_agents = 256
num_buffers = 1
num_threads = 1

[torch]
network = QuadMeshingBoundaryNetwork
encoder = QuadMeshingBoundaryEncoder
decoder = QuadMeshingBoundaryDecoder

[policy]
pos_bands = 4
n_neighbors = 3
source_hidden_size = 128
target_hidden_size = 128
num_layers = 3

# source_encoder_type = ring
# source_encoder_type = se2
source_encoder_type = perceiver

se2_source_layers = 3

perceiver_d_model=128
perceiver_num_latents=32
perceiver_layers=4
perceiver_heads=8
perceiver_mlp_ratio=2
perceiver_dropout=0.0

max_frontier = 256
max_degree = 8
max_candidates = 768

[env]
seed = 42

# Env settings
boundary_mode = True
# episode_max_length = 128
episode_max_length = 400
candidate_rings = 12
candidate_angles = 64
# candidate_radius_min = 0.15
# candidate_radius_max = 0.20
# target_quad_area = 0.015625
candidate_radius_min = 0.025
candidate_radius_max = 0.07
target_quad_area = 0.0009
# boundary_paths = [ "./resources/quad_meshing/boundaries/square.json" ]
boundary_paths = [ "./resources/quad_meshing/boundaries/dolphin.json" ]

# Rewards
reward_invalid = -0.1

# Perf
max_degree = 8
grid_res = 16
grid_cell_size = 0.0625
grid_cell_cap = 8
intersection_tol = 1e-3

# Rendering
render_target_fps = 144
render_width = 1200
render_height = 900
render_show_frontier = True
render_show_candidates = True
render_line_thickness = 2.0
render_point_radius = 4.0
render_candidate_radius = 3.0

[train]
seed = 42
total_timesteps = 5_000_000
learning_rate = 0.01
anneal_lr = True
min_lr_ratio = 0.1
gamma = 0.98
# gamma = 0.995
gae_lambda = 0.95
replay_ratio = 1.0
ent_coef = 0.001
minibatch_size = 1024
horizon = 64
