[base]
package = ocean
env_name = puffer_quad_meshing
# policy_name = Policy
policy_name = QuadMeshingPolicy
rnn_name = None

[vec]
num_envs = 8
num_workers = 8

[env]
num_envs = 256

# boundary_folder = "./boundaries/test"
# boundary_names = ["dolphin.json"]

boundary_folder = "./boundaries/train"
boundary_names = []

observation_radius = 2
observe_remaining_area = True
observe_local_radius = False
observe_boundary_cost = True
n_neighbors = 3
n_sdf_samples = 1

action_radius = 2
# fixed_local_radius = 0.12
cartesian_actions = False
edge_mode = False

delayed_rewards = False
random_active_vertex = False

render_enabled = False
render_target_fps = 60

export_meshes = False
export_mesh_path = "./meshes/mesh_{episode}.obj"

[train]
# total_timesteps = 100_000_000
# # update_epochs = 3
# # gamma = 0.997
# # gae_lambda = 0.95
# gamma = 0.8
# gae_lambda = 0.95
# learning_rate = 30e-4
# anneal_lr = True
# min_lr_ratio = 0.1
# # prio_alpha = 0.8
# # prio_beta0 = 0.2
# # vf_coef = 0.5
# # vf_clip_coef = 0.1
# # clip_coef = 0.1
# ent_coef = 0.001
# bptt_horizon = 64
# # batch_size = 32768
# # batch_size = 65536
# # batch_size = 131072
# batch_size = 262144
# # batch_size = 524288
# # batch_size = 1048576
# minibatch_size = 16384
# # minibatch_size = 32768
# max_minibatch_size = 65536
# # batch_size = 8196
# # minibatch_size = 512

gamma = 0.817341293154591
vf_coef = 3.104497124300082
adam_eps = 1.626843879729962e-12
ent_coef = 0.0006005601822237097
anneal_lr = true
clip_coef = 0.18735587343159785
adam_beta1 = 0.973194707637312
adam_beta2 = 0.9963506822643666
batch_size = 262144
gae_lambda = 0.9657768279016083
prio_alpha = 0.4827029063094817
prio_beta0 = 0.09999999999999998
bptt_horizon = 64
min_lr_ratio = 0.11929941555372124
vf_clip_coef = 0.1
learning_rate = 0.011652632705645618
max_grad_norm = 1.3601009972145974
update_epochs = 1
vtrace_c_clip = 1.8289736227050015
minibatch_size = 16384
total_timesteps = 55209530.23590377
vtrace_rho_clip = 0.9100124787808984
max_minibatch_size = 65536


[sweep.env.observe_remaining_area]
distribution = int_uniform
min = 0
max = 1
scale = auto

[sweep.env.observe_boundary_cost]
distribution = int_uniform
min = 0
max = 1
scale = auto

# [sweep.env.edge_mode]
# distribution = int_uniform
# min = 0
# max = 1
# scale = auto
#
# [sweep.env.n_neighbors]
# distribution = int_uniform
# min = 1
# max = 5
# scale = auto
#
# [sweep.env.n_sdf_samples]
# distribution = int_uniform
# min = 0
# max = 5
# scale = auto
