[base]
package = ocean
env_name = puffer_quad_meshing
# policy_name = Policy
policy_name = QuadMeshingPolicy
rnn_name = None

[vec]
num_envs = 8
num_workers = 8

[env]
num_envs = 1024

# boundary_file = "./boundaries/square.json"
# observation_density = 5
# observation_radius = 0.5
# action_radius = 0.3
boundary_file = "./boundaries/dolphin.json"
observation_density = 7
observation_radius = 0.1
action_radius = 0.06
# boundary_file = "./boundaries/asterisk3.json"
# observation_density = 7
# observation_radius = 0.3
# action_radius = 0.15

delayed_rewards = False
random_active_vertex = False

render_enabled = False
render_target_fps = 60

export_meshes = False
export_mesh_path = "./meshes/mesh_{episode}.obj"

[train]
total_timesteps = 200_000_000
update_epochs = 3
gamma = 0.99
gae_lambda = 0.98
# gae_lambda = 0.95
learning_rate = 1e-3
# vf_coef = 0.5
# vf_clip_coef = 0.1
# clip_coef = 0.1
# ent_coef = 0.005
bptt_horizon = 128
# batch_size = 262144
batch_size = 1048576
minibatch_size = 16384
max_minibatch_size = 65536
# batch_size = 8196
# minibatch_size = 512






# [base]
# package = ocean
# env_name = puffer_quad_meshing
# policy_name = QuadMeshingPolicy
# rnn_name = None
#
# [vec]
# num_envs = 8
# num_workers = 8
#
# [env]
# num_envs = 1024
# boundary_file = "./boundaries/square.json"
# delayed_rewards = False
#
# [train]
# total_timesteps = 200_000_000
# gamma = 0.99
# gae_lambda = 0.98
# learning_rate = 1e-3
# bptt_horizon = 128
# batch_size = 1048576
# minibatch_size = 16384
