[base]
package = ocean
env_name = puffer_quad_meshing_ee
policy_name = Policy
rnn_name = None

[vec]
num_envs = 8
num_workers = 8

[env]
boundary_file = "../EE-568-quad-meshing/boundaries/dolphin_boundary.json"
neighbor_count = 3
fov_point_count = 5
# render_mode = "human"
# boundary_idx = 0

[train]
total_timesteps = 100_000
update_epochs = 3
gamma = 0.99
gae_lambda = 0.95
learning_rate = 3e-4
bptt_horizon = 128
batch_size = 8196
minibatch_size = 512
