#pragma once

#define DEFAULT_MAX_VERTICES 256
#define DEFAULT_MAX_EDGES 512
#define DEFAULT_MAX_FRONTIER 128
#define DEFAULT_MAX_EXISTING_TARGETS 256
#define DEFAULT_MAX_CANDIDATES 64
#define DEFAULT_MAX_TARGETS (DEFAULT_MAX_EXISTING_TARGETS + DEFAULT_MAX_CANDIDATES)
#define DEFAULT_MAX_QUADS 512
#define DEFAULT_MAX_DEGREE 12
#define DEFAULT_MAX_BOUNDARY_POINTS 256

#define OBS_HEADER_SIZE 18
#define OBS_VERTEX_STRIDE 6
#define OBS_EDGE_STRIDE 4
#define DEFAULT_OBS_VERTEX_SIZE (DEFAULT_MAX_VERTICES * OBS_VERTEX_STRIDE)
#define DEFAULT_OBS_EDGE_SIZE (DEFAULT_MAX_EDGES * OBS_EDGE_STRIDE)
#define DEFAULT_OBS_FRONTIER_SIZE DEFAULT_MAX_FRONTIER
#define DEFAULT_OBS_SOURCE_MASK_SIZE DEFAULT_MAX_FRONTIER
#define DEFAULT_OBS_EXISTING_TARGET_SIZE DEFAULT_MAX_EXISTING_TARGETS
#define DEFAULT_OBS_CANDIDATE_SIZE (DEFAULT_MAX_CANDIDATES * 2)
#define DEFAULT_OBS_TARGET_MASK_SIZE (DEFAULT_MAX_FRONTIER * DEFAULT_MAX_TARGETS)
#define DEFAULT_OBS_VERTEX_OFFSET OBS_HEADER_SIZE
#define DEFAULT_OBS_EDGE_OFFSET (DEFAULT_OBS_VERTEX_OFFSET + DEFAULT_OBS_VERTEX_SIZE)
#define DEFAULT_OBS_FRONTIER_OFFSET (DEFAULT_OBS_EDGE_OFFSET + DEFAULT_OBS_EDGE_SIZE)
#define DEFAULT_OBS_SOURCE_MASK_OFFSET (DEFAULT_OBS_FRONTIER_OFFSET + DEFAULT_OBS_FRONTIER_SIZE)
#define DEFAULT_OBS_EXISTING_TARGET_OFFSET (DEFAULT_OBS_SOURCE_MASK_OFFSET + DEFAULT_OBS_SOURCE_MASK_SIZE)
#define DEFAULT_OBS_CANDIDATE_OFFSET (DEFAULT_OBS_EXISTING_TARGET_OFFSET + DEFAULT_OBS_EXISTING_TARGET_SIZE)
#define DEFAULT_OBS_TARGET_MASK_OFFSET (DEFAULT_OBS_CANDIDATE_OFFSET + DEFAULT_OBS_CANDIDATE_SIZE)
#define DEFAULT_OBS_SIZE (DEFAULT_OBS_TARGET_MASK_OFFSET + DEFAULT_OBS_TARGET_MASK_SIZE)
